when serializing remote collection, use dummy user if missing
resolve FATAL:
NoMethodError (undefined method `deep_symbolize_keys' for nil:NilClass):
  app/serializers/collection_serializer.rb:26:in `shared_to