downgrade npm pack html2pdf to 0.9.3 due to webpack compilation issue
Compilation failed:
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'process/browser' in '/chemotion/app/node_modules/canvg/lib'